version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: Add tools
          command: apt-get update && apt-get -y install cppcheck gcc make astyle colordiff
      - run:
          name: Check
          command: make check 
      - run:
          name: Build
          command: make
